[package]
name = "injective-staker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[features]
# use library feature to disable all instantiate/execute/query exports
library = []
test = []

[dependencies]
cosmwasm-schema = "2.1.3"
cosmwasm-std = { version = "2.1.3", features = [
  "cosmwasm_2_0", "staking"
] }
cw-storage-plus = "2.0.0"
cw2 = "2.0.0"
schemars = "0.8.21"
serde = { version = "1.0.210", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.63" }
cw20-base = {version = "2.0.0", features = ["library"]}
cw20 = "2.0.0"
cw-utils = "2.0.0"
cw-controllers = "2.0.0"

[dev-dependencies]
cw-multi-test = { version = "2.1.1", features = ["staking"]}
injective-test-tube = { version = "1.13.2"  }
